// Generated by GBA Studio - font registry (P3).
#ifndef GBA_FONT_TABLE_H
#define GBA_FONT_TABLE_H
#include "bn_sprite_font.h"
extern const bn::sprite_font* const gba_fonts[];
extern const unsigned int gba_font_count;
extern const unsigned int gba_default_font_index;
#endif
