// Generated by GBA Studio - font registry data.
#include "font_table.h"
#include "bn_utf8_characters_map_ref.h"
#include "bn_sprite_items_font_font_gbs_mono.h"

static constexpr signed char gbafont_0_widths[] = { 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8 };
static constexpr bn::sprite_font gbafont_0(bn::sprite_items::font_font_gbs_mono, bn::utf8_characters_map_ref(), gbafont_0_widths);
const bn::sprite_font* const gba_fonts[] = {
    &gbafont_0,
};
const unsigned int gba_font_count = 1;
const unsigned int gba_default_font_index = 0;
