// Generated by GBA Studio - boot entry byte-offsets into game_image[].
#ifndef GBA_GAME_ENTRIES_H
#define GBA_GAME_ENTRIES_H
static const unsigned int game_image_entry_init = 0;
static const unsigned int game_image_entry_update = 39;
#endif
