// Generated by GBA Studio (M2) - per-scene background + actor sprite tables.
// M10c: anim_start/anim_len point to [GBA_ANIM_STATES][8] row-major tables
// (one row of 8 engine animations per animation state; state 0 = default).
#ifndef GBA_SCENE_ASSETS_H
#define GBA_SCENE_ASSETS_H
#include "bn_regular_bg_ptr.h"
#include "bn_sprite_item.h"
#include "bn_regular_bg_items_scene0_bg.h"
#include "bn_regular_bg_items_scene1_bg.h"
#include "bn_sprite_items_scene0_sprite_1.h"
static const int GBA_ANIM_STATES = 1;
struct GbaActorSprite {
    const bn::sprite_item* item;
    const unsigned char* anim_start; // [GBA_ANIM_STATES][8]
    const unsigned char* anim_len;
};
static const unsigned char scene0_sprite_1_anim_start[] = { 0, 1, 2, 3, 4, 6, 8, 10 };
static const unsigned char scene0_sprite_1_anim_len[] = { 1, 1, 1, 1, 2, 2, 2, 2 };
static const GbaActorSprite scene0_sprites[] = {
    { nullptr, nullptr, nullptr },
    { &bn::sprite_items::scene0_sprite_1, scene0_sprite_1_anim_start, scene0_sprite_1_anim_len },
};
static const int scene0_sprites_count = 2;
static const GbaActorSprite scene1_sprites[] = {
    { nullptr, nullptr, nullptr },
};
static const int scene1_sprites_count = 1;
inline bn::regular_bg_ptr gba_create_scene_bg(int sceneIdx) {
    switch(sceneIdx) {
        case 0: return bn::regular_bg_items::scene0_bg.create_bg(0, 0);
        case 1: return bn::regular_bg_items::scene1_bg.create_bg(0, 0);
    default: break;
    }
    return bn::regular_bg_items::scene0_bg.create_bg(0, 0);
}
inline const GbaActorSprite* gba_actor_sprite(int sceneIdx, int actorIdx) {
    switch(sceneIdx) {
        case 0: return (actorIdx >= 0 && actorIdx < scene0_sprites_count) ? &scene0_sprites[actorIdx] : nullptr;
        case 1: return (actorIdx >= 0 && actorIdx < scene1_sprites_count) ? &scene1_sprites[actorIdx] : nullptr;
    default: break;
    }
    return nullptr;
}
#endif
