// Generated by GBA Studio - project tileset lookup (matrix slice B).
//
// GB Studio's "Replace Tile" events name a TILESET asset and a tile index
// within it; the engine copies that tile's pixel data over the background tile
// currently shown at a map position. Tilesets therefore have to reach the ROM
// as raw bn::tile data, which the eject emits here.
//
// This COMMITTED BASELINE is empty (no project tilesets), so the engine builds
// standalone; the editor regenerates the file per project, exactly like
// gba_emote_assets.h and gba_user_code.h.
#ifndef GBA_TILESET_ASSETS_H
#define GBA_TILESET_ASSETS_H
#include "bn_tile.h"

// Tile pixel data for a project tileset, or nullptr when the index is unknown.
// `len` receives how many tiles the set holds, so the engine can range-check a
// script's tile index instead of reading past the end of the data.
inline const bn::tile* gba_tileset_tiles(int tilesetIdx, int* len) {
    switch(tilesetIdx) {
    default: break;
    }
    if (len) *len = 0;
    return nullptr;
}
#endif
