// Generated by GBA Studio (M5a) - DMG music track lookup.
#ifndef GBA_MUSIC_ASSETS_H
#define GBA_MUSIC_ASSETS_H
#include "bn_dmg_music_item.h"
#include "bn_dmg_music_items_song_template.h"
inline const bn::dmg_music_item* gba_music_track(int idx) {
    switch(idx) {
        case 0: return &bn::dmg_music_items::song_template;
    default: break;
    }
    return nullptr;
}
#endif
