// Generated by GBA Studio (M2) - per-scene background + actor sprite tables.
#ifndef GBA_SCENE_ASSETS_H
#define GBA_SCENE_ASSETS_H
#include "bn_regular_bg_ptr.h"
#include "bn_sprite_item.h"
#include "bn_regular_bg_items_scene0_bg.h"
#include "bn_regular_bg_items_scene1_bg.h"
#include "bn_sprite_items_scene0_sprite_1.h"
struct GbaActorSprite {
    const bn::sprite_item* item;
    unsigned char anim_start[8];
    unsigned char anim_len[8];
};
static const GbaActorSprite scene0_sprites[] = {
    { nullptr, {0,0,0,0,0,0,0,0}, {0,0,0,0,0,0,0,0} },
    { &bn::sprite_items::scene0_sprite_1, { 0, 1, 2, 3, 4, 6, 8, 10 }, { 1, 1, 1, 1, 2, 2, 2, 2 } },
};
static const int scene0_sprites_count = 2;
static const GbaActorSprite scene1_sprites[] = {
    { nullptr, {0,0,0,0,0,0,0,0}, {0,0,0,0,0,0,0,0} },
};
static const int scene1_sprites_count = 1;
inline bn::regular_bg_ptr gba_create_scene_bg(int sceneIdx) {
    switch(sceneIdx) {
        case 0: return bn::regular_bg_items::scene0_bg.create_bg(0, 0);
        case 1: return bn::regular_bg_items::scene1_bg.create_bg(0, 0);
    default: break;
    }
    return bn::regular_bg_items::scene0_bg.create_bg(0, 0);
}
inline const GbaActorSprite* gba_actor_sprite(int sceneIdx, int actorIdx) {
    switch(sceneIdx) {
        case 0: return (actorIdx >= 0 && actorIdx < scene0_sprites_count) ? &scene0_sprites[actorIdx] : nullptr;
        case 1: return (actorIdx >= 0 && actorIdx < scene1_sprites_count) ? &scene1_sprites[actorIdx] : nullptr;
    default: break;
    }
    return nullptr;
}
#endif
