// Generated by GBA Studio - music track lookup (DMG gbt-player + Maxmod DirectSound).
#ifndef GBA_MUSIC_ASSETS_H
#define GBA_MUSIC_ASSETS_H
#include "bn_dmg_music_item.h"
#include "bn_music_item.h"
#include "bn_dmg_music_items_song_template.h"
// backend per track index: 0 = DMG (gbt-player PSG), 1 = Maxmod (DirectSound).
inline int gba_music_backend(int idx) {
    switch(idx) {
    default: break;
    }
    return 0;
}
inline const bn::dmg_music_item* gba_dmg_music_track(int idx) {
    switch(idx) {
        case 0: return &bn::dmg_music_items::song_template;
    default: break;
    }
    return nullptr;
}
inline const bn::music_item* gba_maxmod_music_track(int idx) {
    switch(idx) {
    default: break;
    }
    return nullptr;
}
#endif
