// Generated by GBA Studio (M4n) - dialogue font (the project's default font).
#ifndef GBA_FONT_ASSETS_H
#define GBA_FONT_ASSETS_H
#include "bn_sprite_font.h"
#include "bn_sprite_items_dialogue_font.h"
constexpr bn::sprite_font gba_dialogue_font(bn::sprite_items::dialogue_font);
#endif
