// Generated by GBA Studio (M8e) - author "Run Custom Code (C++)" snippets.
//
// Each Custom Code event's snippet becomes a gba_user_<n>() function; gba_user_run
// dispatches by index (the VM_USER_CODE op's operand, assigned at eject). This
// COMMITTED BASELINE has no snippets (empty dispatch); the editor regenerates this
// file per project at eject.
//
// Included by hw.cpp (after vm.h + the Butano headers), so a snippet has the full
// author API in scope:
//   * GBA_VAR(idx) - read/write a 16-bit script variable by its runtime index
//                    (script_memory is the VM's variable+stack array, from vm.h;
//                    VM_GLOBAL(idx) is the same access).
//   * bn::*        - any Butano API.
//   * hw_*         - the engine hardware bridge (see hw.h).
// Snippets run as leaf calls from the VM op - do NOT re-enter the VM.
#ifndef GBA_USER_CODE_H
#define GBA_USER_CODE_H

#define GBA_VAR(idx) (script_memory[idx])

inline void gba_user_run(int idx)
{
    (void)idx;
    // (no snippets in the baseline)
}
#endif
