// Generated by GBA Studio (M2) - the project's scene table + start scene.
#include "gba_link.h"
extern unsigned char scene_main_init[];
extern unsigned char actor_player_update[];

static unsigned char * const scene0_updates[] = { actor_player_update };
static const unsigned char scene0_update_actors[] = { 1 };

const GbaScene gba_scenes[] = {
    { scene_main_init, scene0_updates, scene0_update_actors, 1 },
};
const unsigned int gba_scenes_count = 1;
const unsigned int gba_start_scene = 0;
