// Generated by GBA Studio (M10d) - actor emote sprite lookup.
#ifndef GBA_EMOTE_ASSETS_H
#define GBA_EMOTE_ASSETS_H
#include "bn_sprite_item.h"
inline const bn::sprite_item* gba_emote_sprite(int emoteIdx) {
    switch(emoteIdx) {
    default: break;
    }
    return nullptr;
}
#endif
