// Generated by GBA Studio (M4p) - dialogue fonts (project fonts, variable-width).
#ifndef GBA_FONT_ASSETS_H
#define GBA_FONT_ASSETS_H
#include "bn_sprite_font.h"
#include "bn_utf8_characters_map.h"
#include "bn_sprite_items_dialogue_font_0.h"
#include "bn_sprite_items_dialogue_font_1.h"
constexpr int8_t gba_font_0_widths[] = { // advance width per ASCII char 32..126
    4, 2, 6, 7, 6, 5, 6, 3, 3, 3, 6, 6, 3, 6, 2, 7,
    7, 5, 7, 7, 7, 7, 7, 7, 7, 7, 3, 3, 6, 6, 6, 5,
    8, 7, 7, 7, 7, 7, 7, 7, 7, 6, 6, 6, 7, 7, 7, 7,
    7, 7, 7, 7, 6, 7, 6, 7, 7, 6, 6, 3, 7, 3, 4, 5,
    3, 6, 6, 6, 6, 6, 5, 6, 6, 2, 4, 6, 2, 6, 6, 6,
    6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 4, 2, 4, 7,
};
constexpr bn::sprite_font gba_font_0(bn::sprite_items::dialogue_font_0,
    bn::utf8_characters_map_ref(), gba_font_0_widths);
constexpr int8_t gba_font_1_widths[] = { // advance width per ASCII char 32..126
    4, 2, 6, 7, 6, 5, 6, 3, 3, 3, 6, 6, 3, 6, 2, 7,
    7, 5, 7, 7, 7, 7, 7, 7, 7, 7, 3, 3, 6, 6, 6, 5,
    8, 7, 7, 7, 7, 7, 7, 7, 7, 6, 6, 6, 7, 7, 7, 7,
    7, 7, 7, 7, 6, 7, 6, 7, 7, 6, 6, 3, 7, 3, 4, 5,
    3, 6, 6, 6, 6, 6, 5, 6, 6, 2, 4, 6, 2, 6, 6, 6,
    6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 4, 2, 4, 7,
};
constexpr bn::sprite_font gba_font_1(bn::sprite_items::dialogue_font_1,
    bn::utf8_characters_map_ref(), gba_font_1_widths);
constexpr int gba_dialogue_font_count = 2;
inline const bn::sprite_font& gba_dialogue_font(int idx) {
    switch(idx) {
        case 0: return gba_font_0;
        case 1: return gba_font_1;
    default: return gba_font_0;
    }
}
#endif
