// Generated by GBA Studio (M1 linker) - script entry points the engine runs.
#include "gba_link.h"
extern unsigned char scene_main_init[];
extern unsigned char actor_player_update[];
unsigned char * const gba_scene_init = scene_main_init;
unsigned char * const gba_actor_updates[] = { actor_player_update };
const unsigned char gba_actor_update_actors[] = { 1 };
const unsigned int gba_actor_updates_count = 1;
