// Generated by GBA Studio (M4m) - dialogue avatar sprite lookup.
#ifndef GBA_AVATAR_ASSETS_H
#define GBA_AVATAR_ASSETS_H
#include "bn_sprite_item.h"
#include "bn_sprite_items_avatar_0.h"
inline const bn::sprite_item* gba_avatar_sprite(int avatarIdx) {
    switch(avatarIdx) {
        case 0: return &bn::sprite_items::avatar_0;
    default: break;
    }
    return nullptr;
}
#endif
