// Generated by GBA Studio (M4o) - dialogue font (project default, variable-width).
#ifndef GBA_FONT_ASSETS_H
#define GBA_FONT_ASSETS_H
#include "bn_sprite_font.h"
#include "bn_utf8_characters_map.h"
#include "bn_sprite_items_dialogue_font.h"
constexpr int8_t gba_font_widths[] = { // advance width per ASCII char 32..126
    4, 2, 6, 7, 6, 5, 6, 3, 3, 3, 6, 6, 3, 6, 2, 7,
    7, 5, 7, 7, 7, 7, 7, 7, 7, 7, 3, 3, 6, 6, 6, 5,
    8, 7, 7, 7, 7, 7, 7, 7, 7, 6, 6, 6, 7, 7, 7, 7,
    7, 7, 7, 7, 6, 7, 6, 7, 7, 6, 6, 3, 7, 3, 4, 5,
    3, 6, 6, 6, 6, 6, 5, 6, 6, 2, 4, 6, 2, 6, 6, 6,
    6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 4, 2, 4, 7,
};
constexpr bn::sprite_font gba_dialogue_font(bn::sprite_items::dialogue_font,
    bn::utf8_characters_map_ref(), gba_font_widths);
#endif
