// Generated by GBA Studio (M5b) - sound effect lookup.
#ifndef GBA_SFX_ASSETS_H
#define GBA_SFX_ASSETS_H
#include "bn_sound_item.h"
#include "bn_sound_items.h"
inline const bn::sound_item* gba_sfx(int idx) {
    switch(idx) {
        case 0: return &bn::sound_items::sound_beep;
    default: break;
    }
    return nullptr;
}
#endif
