// gbavm - GBA Studio engine
// Copyright (c) 2026 Scott Fernandez
// MIT License - see the LICENSE file.
//
// M2: runs bytecode produced by GBA Studio's emit layer (src/game_script.c)
// instead of a hand-written array. The emitter leaves 32-bit code targets
// (jump/call/...) as zeroed fields plus a relocation table; here we patch each
// field to point into the in-RAM bytecode at load, then execute it.
//
// Two generated blobs: game_script (the start scene's init, run once) and
// actor_update_script (an actor's update script, a persistent per-frame thread
// that self-loops via VM_IDLE/VM_JUMP) -> e.g. a d-pad-controllable walking actor.

#include "bn_core.h"
#include "bn_timer.h"
#include "hw.h"

#include <cstdint>

extern "C" {
#include "vm.h"

// Generated by GBA Studio's linker (src/lib/compiler/gba/emitGbaBytecode.ts):
// every script proc linked into ONE flat image + a flat {field, target} reloc table.
extern unsigned char game_image[];
extern const unsigned int game_image_len;
extern const unsigned short game_image_relocs[]; // flat {field, target} pairs
extern const unsigned int game_image_relocs_count;
}

// Generated boot entry byte-offsets into game_image[] (init + per-frame update).
#include "game_entries.h"

namespace
{
    // Resolve each code target in `blob`: *(blob+field) = &blob[target]. Byte-wise
    // because the field sits at an arbitrary (often unaligned) offset and unaligned
    // 32-bit writes are unsafe on the ARM7TDMI.
    void apply_relocations(unsigned char * blob, const unsigned short * relocs,
                           unsigned int count)
    {
        for(unsigned int i = 0; i < count; ++i)
        {
            const unsigned int field = relocs[i * 2];
            const unsigned int target = relocs[i * 2 + 1];
            const uintptr_t v = reinterpret_cast<uintptr_t>(blob + target);
            blob[field + 0] = uint8_t(v);
            blob[field + 1] = uint8_t(v >> 8);
            blob[field + 2] = uint8_t(v >> 16);
            blob[field + 3] = uint8_t(v >> 24);
        }
    }
}

int main()
{
    bn::core::init();
    bn::timer rng_seed_timer; // free-running; sampled after boot work for a varying seed
    hw_init();

    apply_relocations(game_image, game_image_relocs, game_image_relocs_count);

    // Seed the VM PRNG (GBA has no DIV register) from accumulated boot ticks.
    vm_boot_seed((UWORD)(rng_seed_timer.elapsed_ticks() & 0xFFFF));

    script_runner_init(TRUE);
    script_execute(0, game_image + game_image_entry_init, nullptr, 0);   // scene init: runs once
    script_execute(0, game_image + game_image_entry_update, nullptr, 0); // actor update: per-frame

    while(true)
    {
        script_runner_update(); // run the editor-emitted bytecode
        hw_render();            // push actor state into sprites
        sys_time++;
        bn::core::update();
    }
}
