// gbavm - GBA Studio engine
// Copyright (c) 2026 Scott Fernandez
// MIT License - see the LICENSE file.
//
// M2: runs bytecode produced by GBA Studio's emit layer (src/game_script.c)
// instead of a hand-written array. The emitter leaves 32-bit code targets
// (jump/call/...) as zeroed fields plus a relocation table; here we patch each
// field to point into the in-RAM bytecode at load, then execute it.
//
// Demo program (generated): activate actor 0, then each frame move it right via
// the actor ops + an RPN step, looping forever -> an actor that walks right.

#include "bn_core.h"
#include "hw.h"

#include <cstdint>

extern "C" {
#include "vm.h"

// Generated by GBA Studio's emit layer (src/lib/compiler/gba/emitGbaBytecode.ts).
extern unsigned char game_script[];
extern const unsigned int game_script_len;
extern const unsigned short game_script_relocs[]; // flat {field, target} pairs
extern const unsigned int game_script_relocs_count;
}

namespace
{
    // Resolve each code target: *(field) = &bytecode[target].
    void apply_relocations()
    {
        for(unsigned int i = 0; i < game_script_relocs_count; ++i)
        {
            const unsigned int field = game_script_relocs[i * 2];
            const unsigned int target = game_script_relocs[i * 2 + 1];
            // Byte-wise store: the field is at an arbitrary (often unaligned)
            // offset, and unaligned 32-bit writes are unsafe on the ARM7TDMI.
            const uintptr_t v = reinterpret_cast<uintptr_t>(game_script + target);
            game_script[field + 0] = uint8_t(v);
            game_script[field + 1] = uint8_t(v >> 8);
            game_script[field + 2] = uint8_t(v >> 16);
            game_script[field + 3] = uint8_t(v >> 24);
        }
    }
}

int main()
{
    bn::core::init();
    hw_init();

    apply_relocations();
    script_runner_init(TRUE);
    script_execute(0, game_script, nullptr, 0);

    while(true)
    {
        script_runner_update(); // run the editor-emitted bytecode
        hw_render();            // push actor state into sprites
        sys_time++;
        bn::core::update();
    }
}
