// Generated by GBA Studio - scene registry (P2 scene runtime).
#ifndef GBA_SCENE_TABLE_H
#define GBA_SCENE_TABLE_H
#include "bn_sprite_item.h"
#include "bn_regular_bg_item.h"
#define GBA_NO_OFFSET 0xFFFFFFFFu  // a script-offset field with no script
struct GbaSceneActor {
    const bn::sprite_item* item;
    unsigned char anim_start[8];
    unsigned char anim_len[8];
    unsigned int update_off;   // byte offset into game_image, 0 = none
    unsigned int interact_off;
};
struct GbaSceneTrigger {
    unsigned short left, top, right, bottom;
    unsigned int interact_off;
    unsigned int leave_off;
};
struct GbaScene {
    const bn::regular_bg_item* bg;
    unsigned short width, height;   // tiles
    unsigned int init_off;
    unsigned char n_actors;
    const GbaSceneActor* actors;
    unsigned char n_triggers;
    const GbaSceneTrigger* triggers;
    short scroll_x_min, scroll_x_max, scroll_y_min, scroll_y_max;
};
extern const GbaScene gba_scenes[];
extern const unsigned int gba_scene_count;
extern const unsigned int gba_start_scene;
#endif
