// Generated by GBA Studio - scene registry data.
#include "scene_table.h"
#include "bn_regular_bg_items_scene0_bg.h"
#include "bn_regular_bg_items_scene1_bg.h"
#include "bn_sprite_items_scene0_sprite_1.h"
#include "bn_sprite_items_scene1_sprite_1.h"

static const GbaSceneActor scene0_actors[] = {
    { nullptr, { 0, 0, 0, 0, 0, 0, 0, 0 }, { 0, 0, 0, 0, 0, 0, 0, 0 }, 4294967295, 4294967295 },
    { &bn::sprite_items::scene0_sprite_1, { 0, 1, 2, 3, 4, 5, 6, 7 }, { 1, 1, 1, 1, 1, 1, 1, 1 }, 39, 4294967295 },
};
static const GbaSceneActor scene1_actors[] = {
    { nullptr, { 0, 0, 0, 0, 0, 0, 0, 0 }, { 0, 0, 0, 0, 0, 0, 0, 0 }, 4294967295, 4294967295 },
    { &bn::sprite_items::scene1_sprite_1, { 0, 1, 2, 3, 4, 5, 6, 7 }, { 1, 1, 1, 1, 1, 1, 1, 1 }, 296, 4294967295 },
};
const GbaScene gba_scenes[] = {
    { &bn::regular_bg_items::scene0_bg, 20, 18, 0, 2, scene0_actors, 0, nullptr, 0, 0, 0, 0 },
    { &bn::regular_bg_items::scene1_bg, 20, 18, 257, 2, scene1_actors, 0, nullptr, 0, 0, 0, 0 },
};
const unsigned int gba_scene_count = 2;
const unsigned int gba_start_scene = 0;
