// Generated by GBA Studio - actor index -> Butano sprite + per-direction
// frame ranges (engine order: Down, Right, Up, Left, then the moving set).
#ifndef GBA_SCENE_SPRITES_H
#define GBA_SCENE_SPRITES_H
#include "bn_sprite_item.h"
#include "bn_sprite_items_scene_sprite_1.h"
struct GbaActorSprite {
    const bn::sprite_item* item;
    unsigned char anim_start[8];
    unsigned char anim_len[8];
};
inline const GbaActorSprite* gba_actor_sprite(int index) {
    static const GbaActorSprite table[] = {
    { nullptr, {0,0,0,0,0,0,0,0}, {0,0,0,0,0,0,0,0} },
    { &bn::sprite_items::scene_sprite_1, { 0, 1, 2, 3, 4, 5, 6, 7 }, { 1, 1, 1, 1, 1, 1, 1, 1 } },
    };
    const int count = 2;
    return (index >= 0 && index < count) ? &table[index] : nullptr;
}
#endif
